<h1>Form data</h1>
<p>Enter your data into form below</p>

<form class="form contact-inchoo" action="<?php echo $block->getBaseUrl().'mainpage/form/save'; ?>" id="contact-form"
      method="post" data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="firstname"><span>First name</span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="First Name" value="" class="input-text" type="text"
                    data-validate='{
                    "required":true,
                    "minlength":2
                    }'>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="lastname"><span>Last Name</span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="Last Name" value="" class="input-text" type="text"
                    data-validate='{
                        "required":true,
                        "minlength":2,
                    }'>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="message"><span>Message</span></label>
            <div class="control">
                <textarea name="message" id="message" title="Message" value="" class="input-text"
                    data-validate='{
                        "required":true,
                        "minlength":10
                    }'></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Send</span>
            </button>
        </div>
    </div>
</form>